# exercise 1

In [6]:
import numpy as np

# Create a NumPy array containing numbers from 1 to 10
arr = np.arange(1, 11)

# Reshape the array to a 2x5 matrix
reshaped_arr = arr.reshape(2, 5)

print(reshaped_arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [7]:
import numpy as np

# Create a NumPy array containing numbers from 1 to 20
arr = np.arange(1, 21)

# Extract elements between the 5th and 15th index (excluding 15th index)
extracted_elements = arr[5:15]

print(extracted_elements)


[ 6  7  8  9 10 11 12 13 14 15]


In [8]:
import pandas as pd

# Create a Pandas Series with the given data
fruits = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})

# Add a new item to the series
fruits['pears'] = 4

print(fruits)


apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [9]:
import pandas as pd

# Create a DataFrame with 10 rows of data
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack'],
    'age': [25, 32, 29, 40, 23, 35, 27, 30, 26, 31],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'M']
}

df = pd.DataFrame(data)

print(df)


      name  age gender
0    Alice   25      F
1      Bob   32      M
2  Charlie   29      M
3    David   40      M
4      Eve   23      F
5    Frank   35      M
6    Grace   27      F
7   Hannah   30      F
8      Ian   26      M
9     Jack   31      M


In [10]:
# Add a new column "occupation" to the DataFrame
df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 
                    'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']

print(df)


      name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   32      M     Manager
2  Charlie   29      M     Analyst
3    David   40      M  Programmer
4      Eve   23      F     Manager
5    Frank   35      M     Analyst
6    Grace   27      F  Programmer
7   Hannah   30      F     Manager
8      Ian   26      M     Analyst
9     Jack   31      M  Programmer


In [12]:
# Select rows where age is greater than or equal to 30
df_filtered = df[df["age"] >= 30]

print(df_filtered)


     name  age gender  occupation
1     Bob   32      M     Manager
3   David   40      M  Programmer
5   Frank   35      M     Analyst
7  Hannah   30      F     Manager
9    Jack   31      M  Programmer


In [13]:
# Save the DataFrame to a CSV file
csv_filename = "dataframe.csv"
df.to_csv(csv_filename, index=False)

# Read the CSV file
df_from_csv = pd.read_csv(csv_filename)

# Display the contents of the CSV file
print(df_from_csv)


      name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   32      M     Manager
2  Charlie   29      M     Analyst
3    David   40      M  Programmer
4      Eve   23      F     Manager
5    Frank   35      M     Analyst
6    Grace   27      F  Programmer
7   Hannah   30      F     Manager
8      Ian   26      M     Analyst
9     Jack   31      M  Programmer
